export enum NexusErrorType {
  INVALID_REQUEST = 'INVALID_REQUEST',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  BOOTSTRAP_FAILED = 'BOOTSTRAP_FAILED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  NO_CONTENT = 'NO_CONTENT',

  // TODO: Add more error types
}

export enum HomeserverErrorType {
  SIGNUP_FAILED = 'SIGNUP_FAILED',
  SIGNIN_FAILED = 'SIGNIN_FAILED',
  FETCH_FAILED = 'FETCH_FAILED',
  LOGOUT_FAILED = 'LOGOUT_FAILED',
  INVALID_HOMESERVER_KEY = 'INVALID_HOMESERVER_KEY',
  INVALID_PUBLIC_KEY = 'INVALID_PUBLIC_KEY',
  INVALID_SECRET_KEY = 'INVALID_SECRET_KEY',
  INVALID_SIGNUP_TOKEN = 'Invalid token',
  CREATE_POST_FAILED = 'CREATE_POST_FAILED',
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  USER_ALREADY_EXISTS = 'User already exists',
  AUTH_REQUEST_FAILED = 'AUTH_REQUEST_FAILED',
  PUT_FAILED = 'PUT_FAILED',
}

export enum DatabaseErrorType {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  STREAM_NOT_FOUND = 'STREAM_NOT_FOUND',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  NOT_FOUND = 'NOT_FOUND',
  SAVE_FAILED = 'SAVE_FAILED',
  UPDATE_FAILED = 'UPDATE_FAILED',
  UPSERT_FAILED = 'UPSERT_FAILED',
  DELETE_FAILED = 'DELETE_FAILED',
  CREATE_FAILED = 'CREATE_FAILED',
  FIND_FAILED = 'FIND_FAILED',
  BULK_OPERATION_FAILED = 'BULK_OPERATION_FAILED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  INVALID_DATA = 'INVALID_DATA',
  QUERY_FAILED = 'QUERY_FAILED',

  // Database initialization error types
  DB_INIT_FAILED = 'DB_INIT_FAILED',
  DB_VERSION_MISMATCH = 'DB_VERSION_MISMATCH',
  DB_OPEN_FAILED = 'DB_OPEN_FAILED',
  DB_DELETE_FAILED = 'DB_DELETE_FAILED',
  DB_SCHEMA_ERROR = 'DB_SCHEMA_ERROR',

  // TODO: Add more error types
}

export enum CommonErrorType {
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',

  // Environment error types
  ENV_VALIDATION_ERROR = 'ENV_VALIDATION_ERROR',
  ENV_MISSING_REQUIRED = 'ENV_MISSING_REQUIRED',
  ENV_INVALID_VALUE = 'ENV_INVALID_VALUE',
  ENV_TYPE_ERROR = 'ENV_TYPE_ERROR',
}

export enum SanitizationErrorType {
  POST_NOT_FOUND = 'POST_NOT_FOUND',
}

export type AppErrorType =
  | NexusErrorType
  | DatabaseErrorType
  | CommonErrorType
  | HomeserverErrorType
  | SanitizationErrorType;
